# Generated by Django 4.1.4 on 2023-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_r_app', '0002_project_user_todo_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='update_data',
            field=models.DateTimeField(null=True),
        ),
    ]
