# Generated by Django 4.1.4 on 2023-02-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_r_app', '0003_alter_todo_update_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
